//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GirlsWeekly.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GirlsWeekly.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Girls Weekly 的本地化字符串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Girls After 90 的本地化字符串。
        /// </summary>
        public static string CategoryAfter90 {
            get {
                return ResourceManager.GetString("CategoryAfter90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Girls Autodyne 的本地化字符串。
        /// </summary>
        public static string CategoryAutodyne {
            get {
                return ResourceManager.GetString("CategoryAutodyne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Campus Girls 的本地化字符串。
        /// </summary>
        public static string CategoryCampus {
            get {
                return ResourceManager.GetString("CategoryCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charm Girls 的本地化字符串。
        /// </summary>
        public static string CategoryCharm {
            get {
                return ResourceManager.GetString("CategoryCharm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cool Girls 的本地化字符串。
        /// </summary>
        public static string CategoryCool {
            get {
                return ResourceManager.GetString("CategoryCool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cute Girls 的本地化字符串。
        /// </summary>
        public static string CategoryCute {
            get {
                return ResourceManager.GetString("CategoryCute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Featured 的本地化字符串。
        /// </summary>
        public static string CategoryFeatured {
            get {
                return ResourceManager.GetString("CategoryFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hot Girls 的本地化字符串。
        /// </summary>
        public static string CategoryHot {
            get {
                return ResourceManager.GetString("CategoryHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Models 的本地化字符串。
        /// </summary>
        public static string CategoryModel {
            get {
                return ResourceManager.GetString("CategoryModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        public static string CategoryOthers {
            get {
                return ResourceManager.GetString("CategoryOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plain Girls 的本地化字符串。
        /// </summary>
        public static string CategoryPlain {
            get {
                return ResourceManager.GetString("CategoryPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pure Girls 的本地化字符串。
        /// </summary>
        public static string CategoryPure {
            get {
                return ResourceManager.GetString("CategoryPure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommended 的本地化字符串。
        /// </summary>
        public static string CategoryRecommended {
            get {
                return ResourceManager.GetString("CategoryRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sunny Girls 的本地化字符串。
        /// </summary>
        public static string CategorySunny {
            get {
                return ResourceManager.GetString("CategorySunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to exit? 的本地化字符串。
        /// </summary>
        public static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Like 的本地化字符串。
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
    }
}
